### ISSUE TITLE
Fix snaps

### ISSUE THREAD

**Issue by danilosalvati** [cvdlab/react-planner#1]
- [x] Fix collinear
- [x] Fix double vertices on same position
- [x] Fix obliques snap

**Comment by chrvadala** [comment]
```{"pixelPerUnit":100,"unit":"m","layers":{"layer-1":{"id":"layer-1","altitude":0,"name":"","vertices":{"BywxrkAFC0":{"id":"BywxrkAFC0","x":151,"y":1862,"prototype":"vertices","selected":true,"lines":["SyLxry0YRR"],"areas":[]},"By_gB10K0R":{"id":"By_gB10K0R","x":708,"y":1368,"prototype":"vertices","selected":true,"lines":["SyLxry0YRR"],"areas":[]},"Hkgu1AFAA":{"id":"Hkgu1AFAA","x":540.4955284736193,"y":1516.5587234004167,"prototype":"vertices","selected":false,"lines":["r1O1RYC0"],"areas":[]},"SJ-ukAFA0":{"id":"SJ-ukAFA0","x":768,"y":1778,"prototype":"vertices","selected":false,"lines":["r1O1RYC0"],"areas":[]}},"lines":{"SyLxry0YRR":{"id":"SyLxry0YRR","type":"wall","prototype":"lines","vertices":["BywxrkAFC0","By_gB10K0R"],"holes":[],"selected":true,"properties":{"height":{"length":3,"unit":"m"},"thickness":{"length":20,"unit":"cm"},"textureA":"none","textureB":"none"}},"r1O1RYC0":{"id":"r1O1RYC0","type":"wall","prototype":"lines","vertices":["Hkgu1AFAA","SJ-ukAFA0"],"holes":[],"selected":false,"properties":{"height":{"length":3,"unit":"m"},"thickness":{"length":20,"unit":"cm"},"textureA":"none","textureB":"none"}}},"holes":{},"areas":{},"items":{},"selected":{"vertices":["BywxrkAFC0","By_gB10K0R"],"lines":["SyLxry0YRR"],"holes":[],"areas":[],"items":[]},"visible":true}},"selectedLayer":"layer-1","width":3000,"height":2000}```

**Comment by chrvadala** [comment]
function intersectionFromTwoLineSegment({x: x1, y: y1}, {x: x2, y: y2}, {x: x3, y: y3}, {x: x4, y:y4}) {
    //https://github.com/psalaets/line-intersect/blob/master/lib/check-intersection.js


    let denom = ((y4 - y3) * (x2 - x1)) - ((x4 - x3) * (y2 - y1));
    let numA = ((x4 - x3) * (y1 - y3)) - ((y4 - y3) * (x1 - x3));
    let numB = ((x2 - x1) * (y1 - y3)) - ((y2 - y1) * (x1 - x3));

    if (denom == 0) {
        if (numA == 0 && numB == 0) {
            return {type: "colinear"};
        }
        return {type: "parallel"};
    }

    var uA = numA / denom;
    var uB = numB / denom;

    if (uA >= 0 && uA <= 1 && uB >= 0 && uB <= 1) {
        let point = {
            x: x1 + (uA * (x2 - x1)),
            y: y1 + (uA * (y2 - y1))
        };
        return {type: "intersecting", point};
    }

    return {type: "none"};
}

function closestPointFromLineSegment(x1, y1, x2, y2, xp, yp) {
    if (x1 === x2) return {x: x1, y: yp};
    if (y1 === y2) return {x: xp, y: y1};

    let m = (y2 - y1) / (x2 - x1);
    let q = y1 - m * x1;

    let mi = -1 / m;
    let qi = yp - mi * xp;

    let x = (qi - q) / (m - mi);
    let y = (m * x + q);

    return {x, y};
}


var p1 = closestPointFromLineSegment(151, 1862, 708, 1368, 541, 1517);
console.log('p1', p1)

// var r = intersectionFromTwoLineSegment(
//     {x:151, y:1862}, {x:708, y:1368},
//     {x: 540.4955284736193,    y: 1516.5587234004167}, {x: 768, y: 1778}
// );
var inters = intersectionFromTwoLineSegment(
    {x: 151, y: 1862}, {x: 708, y: 1368},
    {x: p1.x, y: p1.y}, {x: 768, y: 1778}
 );
console.log('inters', inters);

**Comment by federicospini** [comment]
Use this test instead:

```
...
if (uA >= (0 - e) && uA <= (1 + e) && uB >= (0 - e) && uB <= (1 + e)) {
   ...       
}
...
```

**Comment by chrvadala** [comment]
BUG 2 SNAP
```
ReactPlanner.do([
ReactPlanner.linesActions.selectToolDrawingLine('wall'),
ReactPlanner.linesActions.beginDrawingLine('layer-1', 80, 1800),
ReactPlanner.linesActions.endDrawingLine(100, 1800),
ReactPlanner.linesActions.beginDrawingLine('layer-1', 300, 1800),
ReactPlanner.linesActions.endDrawingLine(150, 1800),
]);
```
