### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by jakeNiemiec** [cvdlab/react-planner#102]
Is this project abandoned?

![image](https://user-images.githubusercontent.com/16782063/35926926-09c699c0-0bef-11e8-92f5-91a2fa3699ea.png)

If so, I'll continue to push changes here: https://github.com/jakeNiemiec/react-floorplanner

**Comment by danilosalvati** [comment]
Hi @jakeNiemiec,
We are very busy with other projects at the moment, but I hope we'll soon release new patches and functionalities for react-planner :smile:

**Comment by jakeNiemiec** [comment]
Thanks, I am working on a private fork of this and would love to contribute
back where welcome.
