### ISSUE TITLE
[BUG] Problem when i draw room into room

### ISSUE THREAD

**Issue by AnthonyBASTIDE** [cvdlab/react-planner#104]
Hello everyone,

I have problem when i try to make a room into an another room, i recorded the scene : https://webmshare.com/dvAYY

(sorry for my english, i'm french).

Have a nice day.
Regards, Anthony.

**Comment by danilosalvati** [comment]
Hi @AnthonyBASTIDE,
this is caused by a bug we had already solved in past versions of the software, probably one of our last commits caused the regression. I will take a look soon...

**Comment by alessiocarrafa** [comment]
Should be fixed with 1.7.2 version

**Comment by AnthonyBASTIDE** [comment]
Thanks guys, now it's ok. 

Have a nice day.
Regards, Anthony.
