### ISSUE TITLE
Memory leak when switching from 2D to 3D few times.

### ISSUE THREAD

**Issue by aw-devel** [cvdlab/react-planner#108]
Hello today I was testing a little your demo APP and as I can see componentWillUnmount in Viewer3d is not properly clean all memory. After switching view from 2d to 3d few times memory usage is growing and growing until 100% and then it's crashing website. 

Can you tell me if I can somehow clean all 3D scene after leave from component in other way?

**Comment by alessiocarrafa** [comment]
Hello, we will investigate on it. Thanks for report

**Comment by aw-devel** [comment]
Looks like fixed in 1.8.4

**Comment by danilosalvati** [comment]
Perfect :+1:
