### ISSUE TITLE
How to create custom items?

### ISSUE THREAD

**Issue by jan0991** [cvdlab/react-planner#109]
Hi, I can't find any tutorial on how to change catalog items. As far as I can tell from example every object is custom JS?

Anyway to make it work like blueprint3d where objects are simple blender exports(if I understand correctly)?

https://github.com/furnishup/blueprint3d/blob/master/example/models/js/gus-churchchair-whiteoak.js#L6

**Comment by alessiocarrafa** [comment]
Hi, we made a basic documentation on how to add Element into Catalog. You can find it in "develop" branch or wait some days for the next patch version
