### ISSUE TITLE
Is it possible to hook line to the nearest round meter

### ISSUE THREAD

**Issue by aw-devel** [cvdlab/react-planner#112]
Hello,

Is it possible to configure drawing walls with epsilon -+2cm that hooks to the nearest full meter

![image](https://user-images.githubusercontent.com/17030931/39626515-8844670e-4fa2-11e8-988b-0d432d48bfcf.png)

In this case it should round to 400cm

**Comment by alessiocarrafa** [comment]
you can use the snap to grid since the grid step measure 1m or, in v2, you can use guides
