### ISSUE TITLE
A and B side on 2D or 3D are reversed

### ISSUE THREAD

**Issue by aw-devel** [cvdlab/react-planner#113]
When draw plan in 2D mode and select wall the A and B is displayed in "reversed" order.

To reproduce it. Create wall, select and try to fill it by Bricks eg, switch to 3D model, Bricks will be displayed on wrong side.

**Comment by alessiocarrafa** [comment]
Thanks for reporting, will be fixed in the next version

**Comment by alessiocarrafa** [comment]
fixed in v2
