### ISSUE TITLE
Error on demo site 

### ISSUE THREAD

**Issue by jakeNiemiec** [cvdlab/react-planner#122]
Demo @ https://cvdlab.github.io/react-planner/ seems to be broken.

![image](https://user-images.githubusercontent.com/16782063/43025003-bd0226dc-8c35-11e8-9526-f28f9ad07f5f.png)

**Comment by danilosalvati** [comment]
Have you tried to clean your browser local storage?

**Comment by jakeNiemiec** [comment]
That worked, thank you!
