### ISSUE TITLE
Image catalog - adding image URI or clicking on image handler show black page

### ISSUE THREAD

**Issue by zuls** [cvdlab/react-planner#123]
I was trying to add an image in the background but it is taking to a blank page. 

1. Go to "Open catalog"
2. Chose "Image" 
3. Add the image catalog in the stage. 
4. Locate Image URI field from the right panel 
5. Add any image url. e.g. https://www.arditesbd.com/wp-content/uploads/2016/09/BizSpark_150-150x66.jpg

Actual result: 
A blank page displays 

Please see the attached image and a video link. 
![image](https://user-images.githubusercontent.com/6715297/43034359-ebb50450-8cfc-11e8-94f2-485176a52bf6.png)

![image](https://user-images.githubusercontent.com/6715297/43034365-f561fed6-8cfc-11e8-9179-a9081781303a.png)

![image](https://user-images.githubusercontent.com/6715297/43034368-ff65f220-8cfc-11e8-8a3d-f43fef2f0887.png)

Video: 
https://drive.google.com/open?id=1lA-DHL56voCgavmGIswLo-RIiVAgpVls

Thanks!

**Comment by danilosalvati** [comment]
Hi @zuls,
I think I have solved this issue (see last commit on the develop branch), however we will need to do more tests before releasing this patch... I hope we can do it soon

**Comment by zuls** [comment]
Thanks @danilosalvati it works!
Tested with: 
- Add image URI -> image is loading fine. 
- Scaled the image 
- Save and load project -> image is loaded in the correct layer.

**Comment by zuls** [comment]
Just noticed the side effect of the fix. 

adding window or door items on the wall is taking to a blank screen.

**Comment by zuls** [comment]
adding window or door items on the wall is working now. Thanks @danilosalvati
