### ISSUE TITLE
texture image disappear when moving objects (loading image texture issue)

### ISSUE THREAD

**Issue by nasriachref** [cvdlab/react-planner#128]
when you choose any cataloge item that has image texture (example "bookcase") and placed in 2d viewer then switch between 2d and 3d while moving it the texture disappear

steps to reproduce :

1. choose catalogue item "bookcase" and placed in 2D viewer.
2. go to 3D viewer ( the model is fine here)
3. return to 2d viewer and move it in 2d space with the mouse
4. go back to the 3d veiwer => texture image is gone the model is now white no texture

**Comment by danilosalvati** [comment]
Duplicated of #114
