### ISSUE TITLE
Creating Objects and Issues in Demo Build

### ISSUE THREAD

**Issue by roryimacit** [cvdlab/react-planner#130]
Hi, I downloaded the 'react-planner-master' file from this repository and have been using it to run react-planner locally however I've been experiencing a few errors such as walls missing textures and items i.e. sofa not appearing in 3D. Would anyone know why these issues would occur when ran locally from the file.

I also have a query about how to create new items in the catalogue. I've tried copying an existing item in the src catalog, renaming the files, editing the planner-element.jsx, editing the mycatalog.js and editing the catalog under dist to reflect the changes I've made but I can't make any new items appear in the catalogue.

Any help would be greatly appreciated as I'm new to using react-planner.

**Comment by danilosalvati** [comment]
Hi @roryimacit,
the issue in the first question seems strange as we usually use the planner locally for development... Have you started the project using  `npm start` or are you serving the static pages with a local webserver? This step is required as threejs cannot load textures or models without a webserver for security reasons...

For the second question, it seems you have followed  all required steps for a new catalog element... There are any errors in the developer console?

**Comment by roryimacit** [comment]
Hi @danilosalvati,

I tried started the project through visual studio code using 'npm start' and received these errors, maybe it'll help you determine where it is exactly I'm going wrong:

> react-planner@2.0.2 start C:\Users\roryc\OneDrive\Documents\react-planner-master\react-planner-master
> webpack-dev-server --inline --config demo/webpack.config.js --port 9000 --mode development

'webpack-dev-server' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-planner@2.0.2 start: `webpack-dev-server --inline --config demo/webpack.config.js --port 9000 --mode development`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-planner@2.0.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\roryc\AppData\Roaming\npm-cache\_logs\2018-08-03T10_37_08_295Z-debug.log
PS C:\Users\roryc\OneDrive\Documents\react-planner-master\react-planner-master>

**Comment by danilosalvati** [comment]
It seems like you forgot to install dependencies using `npm install`

**Comment by roryimacit** [comment]
Thanks @danilosalvati! Everything is running hunky dory for me now, I'll test and see if I can get my catalogue issue to occur.

**Comment by roryimacit** [comment]
That's me flying now, objects are appearing in the catalogue no bother, thanks for your help @danilosalvati

**Comment by danilosalvati** [comment]
You are welcome :smile:
