### ISSUE TITLE
How to Add Variables to the JSON

### ISSUE THREAD

**Issue by rorycor** [cvdlab/react-planner#146]
I need to know how to add a custom variable to the JSON when it is being saved

**Comment by nasriachref** [comment]
add a new member to the State object( after 'export class State extends Record({ ' ) in src/models.js for exemple `customData : {}`  then  in src/components/toolbar/toolbar-save-button.jsx
ge to the function  ' let saveProjectToFile = e =>'   and  add value to the new variable of state object like this line :
`state= state.set(['customData '], customvalue);`
