### ISSUE TITLE
How to Change a Property Programmatically

### ISSUE THREAD

**Issue by rorycor** [cvdlab/react-planner#147]
Is there anyway to update a property programmatically so that its value changes, at the minute it seems properties are setup with default values and can't be written to?

**Comment by nasriachref** [comment]
you cans specify the type of the property  as hidden so nobody can write to it  and if you need to update it programmatically you need to get  the item from the state object like this :
 
`let item = state.getIn(['scene', 'layers', layerID, 'items', itemID]);` // get the item 
for exemple i want to change the property  width from 0 to 150 : 
`properties = item .properties.setIn(['width', 'length'], 150);
properties = item .properties.setIn(['width', 'length'], 150);`// both instructions is needed to change in UI
finally submit to the state object : 
`state = state.setIn(['scene', 'layers', layerID, 'items', itemID, 'properties'], properties);`
