### ISSUE TITLE
Last Selected Item Going Behind Items

### ISSUE THREAD

**Issue by rorycor** [cvdlab/react-planner#148]
![issue](https://user-images.githubusercontent.com/42002101/45824423-e2013f80-bce7-11e8-923f-5e8e514ec36c.PNG)

Anyway to prevent the list of last selected items going behind the items?

**Comment by rorycor** [comment]
Changing the catalog-list.jsx made no changes

**Comment by nasriachref** [comment]
go to  src/components/catalog-view/catalog-list.jsx : 
look for : 
`const searchContainer = {
  width: '100%',
  height: '3em',
  padding: '0.625em',
  background: '#f7f7f9',
  border: '1px solid #e1e1e8',
  cursor: 'pointer',
  position: 'relative',
  boxShadow: '0 1px 6px 0 rgba(0, 0, 0, 0.11), 0 1px 4px 0 rgba(0, 0, 0, 0.11)',
  borderRadius: '2px',
  transition: 'all .2s ease-in-out',
  WebkitTransition: 'all .2s ease-in-out',
  marginBottom: '1em'
};`

change height: '3em'  to  height: '6em'

**Comment by rorycor** [comment]
awesome, thanks for your answers to this and the last question

**Comment by nasriachref** [comment]
you're welcome 👍
