### ISSUE TITLE
Converting Default Unit from 'cm' to 'mm'

### ISSUE THREAD

**Issue by rorycor** [cvdlab/react-planner#150]
Is this feasible? Where would the changes need to start being made as a unit change would impact the item measurements as well as 2d and 3d rulers?

**Comment by nasriachref** [comment]
short answer :  maybe .
  all you need to know first is that all inial measurements convertion  are handled by the catalog module of react-planner in addition to the inial state of the scene,  meaning that you have to edit 2 scripts basicly : 
-'models.js'  path:'src/models.js'
-'catalog.js '   path :'src/catalog/catalog.js'

now keep in mind that you will alter the default measurement unit not the values themselfs meaning 
the previous saved projects will keep the values just with a different unit so you need to convert them manually but future projects will be treated with the new default unit in mind wich is 'mm' and this how to do so : 

1. models.js:
scroll down until you find the  class 'Scene' in it you will find the field " unit : 'cm' " change it to 
" unit : 'mm' "  that's it you have changed the initial state of the scene model

2. catalog.js:

in it you will find this line : 
`import {UNIT_CENTIMETER} from '../constants';` 
change it to : 
`import {UNIT_CENTIMETER, UNIT_MILLIMETER } from '../constants';` 

make sure you respect the case .

next scroll down a little you will find the default constructor of the class catalog look like this : 

`constructor(unit = UNIT_CENTIMETER) {
    this.elements = {};
    this.categories = {root: {name: 'root', label: '/', elements: [], categories: []}};
    this.propertyTypes = {};
    this.unit = unit;

    this.registerMultiplePropertyType([
      ['color', PropertyColor, PropertyColor],
      ['enum', PropertyEnum, PropertyEnum],
      ['string', PropertyString, PropertyString],
      ['number', PropertyNumber, PropertyNumber],
      ['length-measure', PropertyLengthMeasure, PropertyLengthMeasure],
      ['toggle', PropertyToggle, PropertyToggle],
      ['checkbox', PropertyCheckbox, PropertyCheckbox],
      ['hidden', PropertyHidden, PropertyHidden],
      ['read-only', PropertyReadOnly, PropertyReadOnly]
    ]);
  }`
change it like this : 

`constructor(unit = UNIT_MILLIMETER ) {
    this.elements = {};
    this.categories = {root: {name: 'root', label: '/', elements: [], categories: []}};
    this.propertyTypes = {};
    this.unit = unit;

    this.registerMultiplePropertyType([
      ['color', PropertyColor, PropertyColor],
      ['enum', PropertyEnum, PropertyEnum],
      ['string', PropertyString, PropertyString],
      ['number', PropertyNumber, PropertyNumber],
      ['length-measure', PropertyLengthMeasure, PropertyLengthMeasure],
      ['toggle', PropertyToggle, PropertyToggle],
      ['checkbox', PropertyCheckbox, PropertyCheckbox],
      ['hidden', PropertyHidden, PropertyHidden],
      ['read-only', PropertyReadOnly, PropertyReadOnly]
    ]);
  } `

that's it  i hope it helped you

**Comment by rorycor** [comment]
Cheers again, those changes did the job and I was able to get everything converted from there

**Comment by N00bie-to-Github** [comment]
@nasriachref, I followed the instructions but I used `UNIT_FOOT` instead. However, when I edit the property of a wall for instance it multiplies it by 30.48 which is the equivalent in cm. So if I enter 1 ft for the wall, it converts it to 30.48 ft. Did I miss something?
