### ISSUE TITLE
FaClose export missing in react-icons

### ISSUE THREAD

**Issue by JaccoGoris** [cvdlab/react-planner#166]
After upgrading to v2.0.4 I got the following error

```
./node_modules/react-planner/es/components/sidebar/panel-guides.js
Attempted import error: 'FaClose' is not exported from 'react-icons/fa'.
```

Just letting you know.
I'm going to figure out what's going on and make a PR from my fork if I do.

**Comment by danilosalvati** [comment]
With the last version I updated react-icon package... Probably I forgot to fix that import

**Comment by JaccoGoris** [comment]
I can make a PR for it if you want. But I'm not sure what the icon should be :D

**Comment by JaccoGoris** [comment]
I created a PR for the issue, since the guides also broke in the build, it seemed a bigger issue. :)
