### ISSUE TITLE
Screenshot doesn't work

### ISSUE THREAD

**Issue by rorycor** [cvdlab/react-planner#175]
When I click the screenshot button in 2d it fires the saveSVGScreenshotToFile function but doesn't fire the img.onload function inside it, deleting the onload line to allow the ctx.drawImage and imageBrowserDownload to run only ends up outputting a white square/rectangle.

What's caused the screenshot function to fail and is there a fix?

**Comment by danilosalvati** [comment]
Hi @rorycor,
I just tested the 2D screenshot button and it works well on my machine... What browser are you using?

**Comment by rorycor** [comment]
Hi @danilosalvati I'm using chrome, I tested the issue again and on the online version taking a screenshot works fine however in a local repository of react-planner I've been working on on my machine I can't take a screenshot and it's the same for a version of the planner that's been implemented into a project I've been working on (implementation wasn't managed by me). The odd one here is how it's stopped working in my repo as it was previously working when I was last using it a few months ago, still trying to find what could've caused it atm

**Comment by rorycor** [comment]
Just found I'm on 2.0.2, I'll update to 2.0.5 and test everything again and see if that's me sorted

**Comment by rorycor** [comment]
Just problems stemming from me being on an old version my bad
