### ISSUE TITLE
Modules not found

### ISSUE THREAD

**Issue by StevenGoland** [cvdlab/react-planner#196]
Hello, I downloaded the repo and I'm trying to implement the code. I copied the catalog file from demo into src of project folder and I'm getting the follow errors when running: 

./src/catalog/mycatalog.js
Module not found: Can't resolve './areas/**/planner-element.jsx'

Assuming it's related to the following lines in mycatalog.js:

import * as Areas from "./areas/**/planner-element.jsx";
import * as Lines from "./lines/**/planner-element.jsx";
import * as Holes from "./holes/**/planner-element.jsx";
import * as Items from "./items/**/planner-element.jsx";

Also, initially, I get an error that the imports are below this: 

let catalog = new Catalog();

Which requires me to rearrange the order of the code. The folder was copied exactly, so I'm not sure why the path can't locate the files..

**Comment by StevenGoland** [comment]
Is it possible the ** path is causing issues? Is there an extension or something needed to enable it's usage? Otherwise I'm not sure what's going on. If it's of any help, here's the file structure:
```
  > src
    > app.js
    > catalog
       > mycatalog.js
       > areas
       > holes
       > items
       > lines
       > utils
```

**Comment by StevenGoland** [comment]
I made a stackoverflow relating to this issue: 

https://stackoverflow.com/questions/61597022/module-not-found-when-importing-jsx-file-off-github-using-create-react-app

**Comment by wilsmex** [comment]
I had similar issues.  What made the /demo folder finally compile for me was adding the following after ~ line 48 on the /demo/webpack.config.js file
`"import-glob",`
I then ran `npx webpack` in that folder and it compiled down for me
I also added `npm install babel-loader babel-preset-react` at some point troubleshooting, but am not sure if that had an impact or not...

That 'import-glob' package is referenced in the babel config file, but on in webpack.  It's required to make the "**" style imports work it seems.

**Comment by MaTToX3** [comment]
Did you manage to solve the issue? What did you do?

**Comment by StevenGoland** [comment]
> I had similar issues. What made the /demo folder finally compile for me was adding the following after ~ line 48 on the /demo/webpack.config.js file
> `"import-glob",`
> I then ran `npx webpack` in that folder and it compiled down for me
> I also added `npm install babel-loader babel-preset-react` at some point troubleshooting, but am not sure if that had an impact or not...
> 
> That 'import-glob' package is referenced in the babel config file, but on in webpack. It's required to make the "**" style imports work it seems.

Awesome! Thank you
