### ISSUE TITLE
Adding length of a wall in properties

### ISSUE THREAD

**Issue by chinyart** [cvdlab/react-planner#211]
Hi, for some reason i can't seem to find the length of a wall, except for the height and width, but when i select an element to edit the property, i am able to see it there
Below is an property object of a wall when i log **state** in the console:
![IMG_20201125_003359](https://user-images.githubusercontent.com/16898741/100163969-2768bb00-2eb7-11eb-8933-673d400b3325.jpg)
**As You can see the width is missing for a wall.**

Please how can i add the width of a wall or modify the property of any item to have a complete property as i want, Thank you in advance.

**Comment by danilosalvati** [comment]
Hi @chinyart you can use coordinates (using the vertices list) to compute the length of the wall

**Comment by chinyart** [comment]
Hi @danilosalvati, thank you for your quick response, i really appreciate it, i followed your advice and found this snippet to be used somewhere to get lineLength.

I made use of this method to get the width:
 
```
var x1, x2, y1, y2;
var vertices = this.props.state.getIn(['scene', 'layers', _obj, 'lines', childProperties.id, 'vertices']);

var _state$getIn2 = this.props.state.getIn(['scene', 'layers', _obj, 'vertices', vertices.get(0)]),
x1 = _state$getIn2.x,
y1 = _state$getIn2.y;

var _state$getIn3 = this.props.state.getIn(['scene', 'layers', _obj, 'vertices', vertices.get(1)]),
x2 = _state$getIn3.x,
y2 = _state$getIn3.y;

var width = GeometryUtils.pointsDistance(x1, y1, x2, y2);
```

Vertices as a variable is not empty, but i get an undefined error on **vertices.get(0)**
please what am i doing wrong from the snippet above and what should i do instead?, thank you in advance.
