### ISSUE TITLE
The user cannot set an altitude for an item in the catalog

### ISSUE THREAD

**Issue by danilosalvati** [cvdlab/react-planner#30]

**Comment by chrvadala** [comment]
Are you sure? You can use a custom property..

**Comment by danilosalvati** [comment]
This bug arises when I try to normalize the y position of an item during the creation and modification. However it should be possible for the user to choose a custom y origin for the item

**Comment by danilosalvati** [comment]
Fixed with b53cdb5edfb249352293b4d10261e8084712009c and c0428a4255c1e75d8a45a8df45bae5776a2d3911
