### ISSUE TITLE
Print React Planner version at startup 

### ISSUE THREAD

**Issue by danilosalvati** [cvdlab/react-planner#32]

**Comment by danilosalvati** [comment]
Done by a60fa42a5b1634a2e46a14101d1648cc89cc497a

**Comment by danilosalvati** [comment]
This is not valid without webpack

**Comment by chrvadala** [comment]
https://github.com/yurynix/babel-plugin-define
https://github.com/webpack/docs/wiki/Configuration#outputlibrarytarget

**Comment by danilosalvati** [comment]
Not needed (see #39)

**Comment by chrvadala** [comment]
done by mean of https://github.com/chrvadala/const-version
