### ISSUE TITLE
Label measure drawing a wall

### ISSUE THREAD

**Issue by mivi2007** [cvdlab/react-planner#57]
Accade che se si è in una vista con "poco zoom" e si sta disegnando un muro di dimensioni grandi, e quindi si panning del canvas, l'indicazione della misura - che viene messa al centro - può rischiare di essere "fuori schermo".

1. è possibile fare in modo che una situazione di questo tipo si possa "identificare a codice" e visualizzare quindi la misura nei pressi del tip del mouse (quindi, nei pressi del punto che non ho ancora rilasciato)?

2. in subordine, nel caso in cui non si "possa identificare a codice", la misura dovrebbe essere scritta nei pressi del tip del mouse (che dovrebbe essere sempre visibile
![immagine](https://cloud.githubusercontent.com/assets/923779/20482272/1051f0e2-afec-11e6-9a20-6758e6d8bb27.png)

**Comment by danilosalvati** [comment]
Fixed with 1.1.0
