### ISSUE TITLE
OBJ reloads each time an item with an OBJ is selected

### ISSUE THREAD

**Issue by SpencerIO** [cvdlab/react-planner#72]
OBJ reloads each time an item with an OBJ is selected

This slows down the interface quite a bit and it flickers the item.

**Comment by danilosalvati** [comment]
That's true, we should add a sort of caching systems for objects in the catalog to avoid reloading

**Comment by danilosalvati** [comment]
Commits 8668a3f483bb23c1705d8518630a9bf44406b5cb  766c9151b655684a1cc14a0e4e0c8fb3bc99bece and cfea4cb60db0eb671c9866fae6698c7026e6452e show how a user can cache objs inside a catalog to save computation time
