### ISSUE TITLE
Error build demo

### ISSUE THREAD

**Issue by SalvatoreAD** [cvdlab/react-planner#74]
I try the demo and I have this error:

ERROR in ./demo/src/renderer.jsx
Module parse failed: /root/FloorPlanner/node_modules/react-planner/demo/src/renderer.jsx Unexpected token (49:2)
You may need an appropriate loader to handle this file type.
| ReactDOM.render(
| 
|   <Provider store={store}>
|       <ContainerDimensions>
|         {({width, height}) =>
 @ multi (webpack)-dev-server/client?http://localhost:9000 ./src/renderer.jsx

can you help me?

**Comment by danilosalvati** [comment]
Hi @SalvatoreAD ,

It is a strange behaviour, because files in the demo are the same we have used to build https://cvdlab.github.io/react-planner/ page.

To build the project you should use a module bundler (for example we have used webpack). With our configuration (stored in https://github.com/cvdlab/react-planner/blob/master/demo/webpack.config.js)  you should be able to build the demo running:
`webpack --config demo/webpack.config.js --env.production` 
You should also use a `babel.rc` file (see our in https://github.com/cvdlab/react-planner/blob/master/.babelrc)

Your problem seems related to the lack of a loader for react (are your `.babel.rc` and `webpack.config` files properly configured?)

**Comment by SalvatoreAD** [comment]
Thanks I found the error. -------- Messaggio originale --------Oggetto: Re: [cvdlab/react-planner] Error build demo (#74)Da: Danilo Salvati A: cvdlab/react-planner CC: SalvatoreAD ,Mention Hi @SalvatoreAD ,
It is a strange behaviour, because files in the demo are the same we have used to build https://cvdlab.github.io/react-planner/ page.
To build the project you should use a module bundler (for example we have used webpack). With our configuration (stored in https://github.com/cvdlab/react-planner/blob/master/demo/webpack.config.js)  you should be able to build the demo running:
webpack --config demo/webpack.config.js --env.production
You should also use a babel.rc file (see our in https://github.com/cvdlab/react-planner/blob/master/.babelrc)
Your problem seems related to the lack of a loader for react (are your .babel.rc and webpack.config files properly configured?)

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/cvdlab/react-planner","title":"cvdlab/react-planner","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/cvdlab/react-planner"}},"updates":{"snippets":[{"icon":"PERSON","message":"@danilosalvati in #74: Hi @SalvatoreAD ,\r\n\r\nIt is a strange behaviour, because files in the demo are the same we have used to build https://cvdlab.github.io/react-planner/ page.\r\n\r\nTo build the project you should use a module bundler (for example we have used webpack). With our configuration (stored in https://github.com/cvdlab/react-planner/blob/master/demo/webpack.config.js)  you should be able to build the demo running:\r\n`webpack --config demo/webpack.config.js --env.production` \r\nYou should also use a `babel.rc` file (see our in https://github.com/cvdlab/react-planner/blob/master/.babelrc)\r\n\r\nYour problem seems related to the lack of a loader for react (are your `.babel.rc` and `webpack.config` files properly configured?)"}],"action":{"name":"View Issue","url":"https://github.com/cvdlab/react-planner/issues/74#issuecomment-280306421"}}}

**Comment by danilosalvati** [comment]
Perfect :+1:
