### ISSUE TITLE
Installation on server

### ISSUE THREAD

**Issue by SalvatoreAD** [cvdlab/react-planner#75]
Can I install it on a server?

**Comment by danilosalvati** [comment]
Hi @SalvatoreAD,
of course you can! You just have to compile your own react project with this component (a page example is the demo page in https://github.com/cvdlab/react-planner/blob/master/demo/src/renderer.jsx). At the end of the process you should obtain a web page with javascript files (like the ones in https://github.com/cvdlab/react-planner/tree/gh-pages which were built from our demo) which can be served with your favourite webserver

**Comment by SalvatoreAD** [comment]
Thank's 👍  (Grazie mille xD)

**Comment by danilosalvati** [comment]
:+1:
