### ISSUE TITLE
Background image

### ISSUE THREAD

**Issue by Vanuan** [cvdlab/react-planner#91]
Is it possible to add an image layer. I.e. if I already have a scan of a plan. Couldn't find how to do that.

**Comment by danilosalvati** [comment]
Hi @Vanuan,
you can add a background image choosing the item image from the catalog. However the scaling given by that item is a bit unconfortable, but we are improving it in these days (we just have to solve last bugs :smile:)

![image](https://user-images.githubusercontent.com/6910565/27272895-e19a941c-54cc-11e7-9a9e-9a1fe249cfeb.png)

**Comment by Vanuan** [comment]
Ah, that's counter-intuitive. Thanks.

**Comment by kuzbida** [comment]
@danilosalvati I've faced the same issue and have following question - is it possible to change opacity of image or that's better to create new layer and play with it?

**Comment by danilosalvati** [comment]
I usually have a layer for every background image I want to add to the drawing in order to change visibility order and opacity
