### ISSUE TITLE
Export image

### ISSUE THREAD

**Issue by lsilvs** [cvdlab/react-planner#93]
Is there any way to export an image from the drawn 2D?

**Comment by danilosalvati** [comment]
Hi @lsilvs,
it is not possible at the moment, but we can introduce it with the next releases

**Comment by lsilvs** [comment]
Would be nice :)

Cheers,

**Comment by danilosalvati** [comment]
You can see it with the new demo version :smile:

**Comment by lsilvs** [comment]
Hi @danilosalvati 

Thanks for the reply.

I've just tested it on https://cvdlab.github.io/react-planner/ and the image downloaded is corrupted.

Here is the file exported: https://www.dropbox.com/s/qban5xuykls6rvz/output1501852991946.png?dl=0

Best,
Lucas

**Comment by danilosalvati** [comment]
@lsilvs It was a small bug I didn't notice on my Linux platform. I just solved it and the patch will be released soon

**Comment by lsilvs** [comment]
Cool stuff!

Cheers,
Lucas
