### ISSUE TITLE
General Information: How to render the saved JSON floorplan

### ISSUE THREAD

**Issue by abhilash1in** [cvdlab/react-planner#95]
Once the floor plan is generated and saved as JSON, how to render **just** the floor plan in 2D or 3D and show it to the end user? I also plan to indicate users location on this floor plan by the means of a blue dot (like how Google Maps shows user location). I can get the coordinates where it should be displayed, but how to add it to the floorplan and display it?

**Comment by danilosalvati** [comment]
Hi @abhilash1in,
at the moment our planner does not support a read-only mode. So you can do two things:
- Extend our viewer to support a read-only mode (I'm not sure it's the cleanest option...)
- Define a new floorplan viewer using code in `/src/components/viewer2d` for the end user (you can also insert the blue dot using the current redux action system)

Let us know if you need support :smile:

**Comment by abhilash1in** [comment]
Hi @danilosalvati ,

The second option looks promising. I will try it out.

Can I get your mail ID so that I can discuss more details with you? You can reach me at abhilash1in@gmail.com
