### ISSUE TITLE
2D coordinates to 3D coordinates

### ISSUE THREAD

**Issue by JsonDiv** [cvdlab/react-planner#97]
Hello, only know 2D coordinates in JSON, this program how to convert them to 3d coordinates, can you tell me the concrete formula？

**Comment by danilosalvati** [comment]
Hi @JsonDiv,
coordinates for the 3d viewer are expressed in this way:

2DCoord(x,y) -> 3DCoords(x,<coord defined by the chosen catalog element> + layer.altitude, y)
